/*
 * Swagger Dummy - OpenAPI 3.0
 * This is a sample request
 *
 * OpenAPI spec version: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package tr.com.abcd.rest.api.dummy.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import tr.com.abcd.rest.api.model.RequestHeader;
import io.swagger.v3.oas.annotations.media.Schema;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * Message
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2022-12-22T17:22:12.592Z[GMT]")public class Message   {
  @JsonProperty("requestHeader")
  private RequestHeader requestHeader = null;

  @JsonProperty("processDate")
  private String processDate = null;

  @JsonProperty("isin")
  private String isin = null;

  @JsonProperty("mbrId")
  private String mbrId = null;

  @JsonProperty("addDefCode")
  private String addDefCode = null;

  public Message requestHeader(RequestHeader requestHeader) {
    this.requestHeader = requestHeader;
    return this;
  }

  /**
   * Get requestHeader
   * @return requestHeader
   **/
  @JsonProperty("requestHeader")
  @Schema(required = true, description = "")
  @NotNull
  @Valid
  public RequestHeader getRequestHeader() {
    return requestHeader;
  }

  public void setRequestHeader(RequestHeader requestHeader) {
    this.requestHeader = requestHeader;
  }

  public Message processDate(String processDate) {
    this.processDate = processDate;
    return this;
  }

  /**
   * Get processDate
   * @return processDate
   **/
  @JsonProperty("processDate")
  @Schema(required = true, description = "")
  @NotNull
 @Pattern(regexp="(19([0-9]{2})|2([0-9]{3}))(0[1-9]|1[0-2])(0[1-9]|[1,2][0-9]|3[0-1])")  public String getProcessDate() {
    return processDate;
  }

  public void setProcessDate(String processDate) {
    this.processDate = processDate;
  }

  public Message isin(String isin) {
    this.isin = isin;
    return this;
  }

  /**
   * Get isin
   * @return isin
   **/
  @JsonProperty("isin")
  @Schema(required = true, description = "")
  @NotNull
 @Pattern(regexp="[A-Z0-9]{12}")  public String getIsin() {
    return isin;
  }

  public void setIsin(String isin) {
    this.isin = isin;
  }

  public Message mbrId(String mbrId) {
    this.mbrId = mbrId;
    return this;
  }

  /**
   * Get mbrId
   * @return mbrId
   **/
  @JsonProperty("mbrId")
  @Schema(description = "")
 @Pattern(regexp="[A-Z0-9]*") @Size(min=3,max=8)  public String getMbrId() {
    return mbrId;
  }

  public void setMbrId(String mbrId) {
    this.mbrId = mbrId;
  }

  public Message addDefCode(String addDefCode) {
    this.addDefCode = addDefCode;
    return this;
  }

  /**
   * Get addDefCode
   * @return addDefCode
   **/
  @JsonProperty("addDefCode")
  @Schema(description = "")
 @Pattern(regexp="[A-Z0-9]*") @Size(max=2)  public String getAddDefCode() {
    return addDefCode;
  }

  public void setAddDefCode(String addDefCode) {
    this.addDefCode = addDefCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Message message = (Message) o;
    return Objects.equals(this.requestHeader, message.requestHeader) &&
        Objects.equals(this.processDate, message.processDate) &&
        Objects.equals(this.isin, message.isin) &&
        Objects.equals(this.mbrId, message.mbrId) &&
        Objects.equals(this.addDefCode, message.addDefCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestHeader, processDate, isin, mbrId, addDefCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Message {\n");
    
    sb.append("    requestHeader: ").append(toIndentedString(requestHeader)).append("\n");
    sb.append("    processDate: ").append(toIndentedString(processDate)).append("\n");
    sb.append("    isin: ").append(toIndentedString(isin)).append("\n");
    sb.append("    mbrId: ").append(toIndentedString(mbrId)).append("\n");
    sb.append("    addDefCode: ").append(toIndentedString(addDefCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
