/*
 * Swagger Dummy - OpenAPI 3.0
 * This is a sample request
 *
 * OpenAPI spec version: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package tr.com.abcd.rest.api.dummy.model;

import java.util.Objects;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * RequestBody
 */
public class RequestBody   {
  @JsonProperty("processDate")
  private String processDate = null;

  @JsonProperty("isin")
  private String isin = null;

  @JsonProperty("mbrId")
  private String mbrId = null;

  @JsonProperty("addDefCode")
  private String addDefCode = null;

  public RequestBody processDate(String processDate) {
    this.processDate = processDate;
    return this;
  }

  /**
   * Get processDate
   * @return processDate
   **/
  @JsonProperty("processDate")
  @Schema(required = true, description = "")
  @NotNull
 @Pattern(regexp="(19([0-9]{2})|2([0-9]{3}))(0[1-9]|1[0-2])(0[1-9]|[1,2][0-9]|3[0-1])")  public String getProcessDate() {
    return processDate;
  }

  public void setProcessDate(String processDate) {
    this.processDate = processDate;
  }

  public RequestBody isin(String isin) {
    this.isin = isin;
    return this;
  }

  /**
   * Get isin
   * @return isin
   **/
  @JsonProperty("isin")
  @Schema(required = true, description = "")
  @NotNull
 @Pattern(regexp="[A-Z0-9]{12}")  public String getIsin() {
    return isin;
  }

  public void setIsin(String isin) {
    this.isin = isin;
  }

  public RequestBody mbrId(String mbrId) {
    this.mbrId = mbrId;
    return this;
  }

  /**
   * Get mbrId
   * @return mbrId
   **/
  @JsonProperty("mbrId")
  @Schema(description = "")
 @Pattern(regexp="[A-Z0-9]*") @Size(min=3,max=8)  public String getMbrId() {
    return mbrId;
  }

  public void setMbrId(String mbrId) {
    this.mbrId = mbrId;
  }

  public RequestBody addDefCode(String addDefCode) {
    this.addDefCode = addDefCode;
    return this;
  }

  /**
   * Get addDefCode
   * @return addDefCode
   **/
  @JsonProperty("addDefCode")
  @Schema(description = "")
 @Pattern(regexp="[A-Z0-9]*") @Size(max=2)  public String getAddDefCode() {
    return addDefCode;
  }

  public void setAddDefCode(String addDefCode) {
    this.addDefCode = addDefCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestBody requestBody = (RequestBody) o;
    return Objects.equals(this.processDate, requestBody.processDate) &&
        Objects.equals(this.isin, requestBody.isin) &&
        Objects.equals(this.mbrId, requestBody.mbrId) &&
        Objects.equals(this.addDefCode, requestBody.addDefCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(processDate, isin, mbrId, addDefCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestBody {\n");
    
    sb.append("    processDate: ").append(toIndentedString(processDate)).append("\n");
    sb.append("    isin: ").append(toIndentedString(isin)).append("\n");
    sb.append("    mbrId: ").append(toIndentedString(mbrId)).append("\n");
    sb.append("    addDefCode: ").append(toIndentedString(addDefCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
