/*
 * Swagger Dummy - OpenAPI 3.0
 * This is a sample request
 *
 * OpenAPI spec version: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package tr.com.abcd.rest.api.model;

import java.util.Objects;

import javax.validation.Valid;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * CommonFault
 */
public class CommonFault   {
  @JsonProperty("error")
  private String error = null;

  @JsonProperty("Fault")
  private CommonFaultFault fault = null;

  public CommonFault error(String error) {
    this.error = error;
    return this;
  }

  /**
   * Get error
   * @return error
   **/
  @JsonProperty("error")
  @Schema(description = "")
  public String getError() {
    return error;
  }

  public void setError(String error) {
    this.error = error;
  }

  public CommonFault fault(CommonFaultFault fault) {
    this.fault = fault;
    return this;
  }

  /**
   * Get fault
   * @return fault
   **/
  @JsonProperty("Fault")
  @Schema(description = "")
  @Valid
  public CommonFaultFault getFault() {
    return fault;
  }

  public void setFault(CommonFaultFault fault) {
    this.fault = fault;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommonFault commonFault = (CommonFault) o;
    return Objects.equals(this.error, commonFault.error) &&
        Objects.equals(this.fault, commonFault.fault);
  }

  @Override
  public int hashCode() {
    return Objects.hash(error, fault);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommonFault {\n");
    
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    fault: ").append(toIndentedString(fault)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
