/*
 * Swagger Dummy - OpenAPI 3.0
 * This is a sample request
 *
 * OpenAPI spec version: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package tr.com.abcd.rest.api.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.v3.oas.annotations.media.Schema;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * CommonFaultFault
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2022-12-22T17:22:12.592Z[GMT]")public class CommonFaultFault   {
  @JsonProperty("faultcode")
  private String faultcode = null;

  @JsonProperty("faultstring")
  private String faultstring = null;

  @JsonProperty("faultactor")
  private String faultactor = null;

  @JsonProperty("detail")
  private Object detail = null;

  public CommonFaultFault faultcode(String faultcode) {
    this.faultcode = faultcode;
    return this;
  }

  /**
   * Get faultcode
   * @return faultcode
   **/
  @JsonProperty("faultcode")
  @Schema(description = "")
  public String getFaultcode() {
    return faultcode;
  }

  public void setFaultcode(String faultcode) {
    this.faultcode = faultcode;
  }

  public CommonFaultFault faultstring(String faultstring) {
    this.faultstring = faultstring;
    return this;
  }

  /**
   * Get faultstring
   * @return faultstring
   **/
  @JsonProperty("faultstring")
  @Schema(description = "")
  public String getFaultstring() {
    return faultstring;
  }

  public void setFaultstring(String faultstring) {
    this.faultstring = faultstring;
  }

  public CommonFaultFault faultactor(String faultactor) {
    this.faultactor = faultactor;
    return this;
  }

  /**
   * Get faultactor
   * @return faultactor
   **/
  @JsonProperty("faultactor")
  @Schema(description = "")
  public String getFaultactor() {
    return faultactor;
  }

  public void setFaultactor(String faultactor) {
    this.faultactor = faultactor;
  }

  public CommonFaultFault detail(Object detail) {
    this.detail = detail;
    return this;
  }

  /**
   * Get detail
   * @return detail
   **/
  @JsonProperty("detail")
  @Schema(description = "")
  public Object getDetail() {
    return detail;
  }

  public void setDetail(Object detail) {
    this.detail = detail;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommonFaultFault commonFaultFault = (CommonFaultFault) o;
    return Objects.equals(this.faultcode, commonFaultFault.faultcode) &&
        Objects.equals(this.faultstring, commonFaultFault.faultstring) &&
        Objects.equals(this.faultactor, commonFaultFault.faultactor) &&
        Objects.equals(this.detail, commonFaultFault.detail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(faultcode, faultstring, faultactor, detail);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommonFaultFault {\n");
    
    sb.append("    faultcode: ").append(toIndentedString(faultcode)).append("\n");
    sb.append("    faultstring: ").append(toIndentedString(faultstring)).append("\n");
    sb.append("    faultactor: ").append(toIndentedString(faultactor)).append("\n");
    sb.append("    detail: ").append(toIndentedString(detail)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
