/*
 * Swagger Dummy - OpenAPI 3.0
 * This is a sample request
 *
 * OpenAPI spec version: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package tr.com.abcd.rest.api.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import tr.com.abcd.rest.api.model.ResponseBody;
import tr.com.abcd.rest.api.model.ResponseHeader;
import io.swagger.v3.oas.annotations.media.Schema;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * MkkResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2022-12-22T17:22:12.592Z[GMT]")public class MkkResponse   {
  @JsonProperty("responseHeader")
  private ResponseHeader responseHeader = null;

  @JsonProperty("responseBody")
  private ResponseBody responseBody = null;

  public MkkResponse responseHeader(ResponseHeader responseHeader) {
    this.responseHeader = responseHeader;
    return this;
  }

  /**
   * Get responseHeader
   * @return responseHeader
   **/
  @JsonProperty("responseHeader")
  @Schema(required = true, description = "")
  @NotNull
  @Valid
  public ResponseHeader getResponseHeader() {
    return responseHeader;
  }

  public void setResponseHeader(ResponseHeader responseHeader) {
    this.responseHeader = responseHeader;
  }

  public MkkResponse responseBody(ResponseBody responseBody) {
    this.responseBody = responseBody;
    return this;
  }

  /**
   * Get responseBody
   * @return responseBody
   **/
  @JsonProperty("responseBody")
  @Schema(description = "")
  @Valid
  public ResponseBody getResponseBody() {
    return responseBody;
  }

  public void setResponseBody(ResponseBody responseBody) {
    this.responseBody = responseBody;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MkkResponse mkkResponse = (MkkResponse) o;
    return Objects.equals(this.responseHeader, mkkResponse.responseHeader) &&
        Objects.equals(this.responseBody, mkkResponse.responseBody);
  }

  @Override
  public int hashCode() {
    return Objects.hash(responseHeader, responseBody);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MkkResponse {\n");
    
    sb.append("    responseHeader: ").append(toIndentedString(responseHeader)).append("\n");
    sb.append("    responseBody: ").append(toIndentedString(responseBody)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
