/*
 * Swagger Dummy - OpenAPI 3.0
 * This is a sample request
 *
 * OpenAPI spec version: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package tr.com.abcd.rest.api.model;

import java.util.Objects;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * RequestHeader
 */
public class RequestHeader   {
  @JsonProperty("senderReference")
  private String senderReference = null;

  @JsonProperty("senderMember")
  private String senderMember = null;

  @JsonProperty("sender")
  private String sender = null;

  public RequestHeader senderReference(String senderReference) {
    this.senderReference = senderReference;
    return this;
  }

  /**
   * Get senderReference
   * @return senderReference
   **/
  @JsonProperty("senderReference")
  @Schema(required = true, description = "")
  @NotNull
 @Size(min=1,max=255)  public String getSenderReference() {
    return senderReference;
  }

  public void setSenderReference(String senderReference) {
    this.senderReference = senderReference;
  }

  public RequestHeader senderMember(String senderMember) {
    this.senderMember = senderMember;
    return this;
  }

  /**
   * Get senderMember
   * @return senderMember
   **/
  @JsonProperty("senderMember")
  @Schema(required = true, description = "")
  @NotNull
 @Pattern(regexp="[A-Z0-9]*") @Size(min=3,max=8)  public String getSenderMember() {
    return senderMember;
  }

  public void setSenderMember(String senderMember) {
    this.senderMember = senderMember;
  }

  public RequestHeader sender(String sender) {
    this.sender = sender;
    return this;
  }

  /**
   * Get sender
   * @return sender
   **/
  @JsonProperty("sender")
  @Schema(required = true, description = "")
  @NotNull
 @Pattern(regexp="[A-Z0-9]*") @Size(min=3,max=10)  public String getSender() {
    return sender;
  }

  public void setSender(String sender) {
    this.sender = sender;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestHeader requestHeader = (RequestHeader) o;
    return Objects.equals(this.senderReference, requestHeader.senderReference) &&
        Objects.equals(this.senderMember, requestHeader.senderMember) &&
        Objects.equals(this.sender, requestHeader.sender);
  }

  @Override
  public int hashCode() {
    return Objects.hash(senderReference, senderMember, sender);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestHeader {\n");
    
    sb.append("    senderReference: ").append(toIndentedString(senderReference)).append("\n");
    sb.append("    senderMember: ").append(toIndentedString(senderMember)).append("\n");
    sb.append("    sender: ").append(toIndentedString(sender)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
