/*
 * Swagger Dummy - OpenAPI 3.0
 * This is a sample request
 *
 * OpenAPI spec version: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package tr.com.abcd.rest.api.model;

import java.util.Objects;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;

/**
 * ResponseHeader
 */
public class ResponseHeader   {
  @JsonProperty("senderReference")
  private String senderReference = null;

  @JsonProperty("receiverMember")
  private String receiverMember = null;

  @JsonProperty("messageId")
  private String messageId = null;

  public ResponseHeader senderReference(String senderReference) {
    this.senderReference = senderReference;
    return this;
  }

  /**
   * Get senderReference
   * @return senderReference
   **/
  @JsonProperty("senderReference")
  @Schema(required = true, description = "")
  @NotNull
 @Size(min=1,max=255)  public String getSenderReference() {
    return senderReference;
  }

  public void setSenderReference(String senderReference) {
    this.senderReference = senderReference;
  }

  public ResponseHeader receiverMember(String receiverMember) {
    this.receiverMember = receiverMember;
    return this;
  }

  /**
   * Get receiverMember
   * @return receiverMember
   **/
  @JsonProperty("receiverMember")
  @Schema(required = true, description = "")
  @NotNull
 @Pattern(regexp="[A-Z0-9]*") @Size(min=3,max=8)  public String getReceiverMember() {
    return receiverMember;
  }

  public void setReceiverMember(String receiverMember) {
    this.receiverMember = receiverMember;
  }

  public ResponseHeader messageId(String messageId) {
    this.messageId = messageId;
    return this;
  }

  /**
   * Get messageId
   * @return messageId
   **/
  @JsonProperty("messageId")
  @Schema(description = "")
 @Pattern(regexp="[0-9]{1,15}") @Size(min=1,max=15)  public String getMessageId() {
    return messageId;
  }

  public void setMessageId(String messageId) {
    this.messageId = messageId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseHeader responseHeader = (ResponseHeader) o;
    return Objects.equals(this.senderReference, responseHeader.senderReference) &&
        Objects.equals(this.receiverMember, responseHeader.receiverMember) &&
        Objects.equals(this.messageId, responseHeader.messageId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(senderReference, receiverMember, messageId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseHeader {\n");
    
    sb.append("    senderReference: ").append(toIndentedString(senderReference)).append("\n");
    sb.append("    receiverMember: ").append(toIndentedString(receiverMember)).append("\n");
    sb.append("    messageId: ").append(toIndentedString(messageId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
