/*
 * Swagger Dummy - OpenAPI 3.0
 * This is a sample request
 *
 * OpenAPI spec version: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package tr.com.abcd.rest.api.model;

import java.util.Objects;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

import io.swagger.v3.oas.annotations.media.Schema;
import tr.com.abcd.rest.api.dummy.model.RequestBody;

/**
 * RestMessage
 */
public class RestMessage   {
  @JsonProperty("requestHeader")
  @NotNull
  @Valid
  private RequestHeader requestHeader = null;

  @JsonProperty("requestBody")
  @Valid
  @NotNull
  private RequestBody requestBody = null;

  public RestMessage requestHeader(RequestHeader requestHeader) {
    this.requestHeader = requestHeader;
    return this;
  }

  /**
   * Get requestHeader
   * @return requestHeader
   **/
  @JsonProperty("requestHeader")
  @Schema(required = true, description = "")
  @NotNull
  @Valid
  public RequestHeader getRequestHeader() {
    return requestHeader;
  }

  public void setRequestHeader(RequestHeader requestHeader) {
    this.requestHeader = requestHeader;
  }

  public RestMessage request(RequestBody requestBody) {
    this.requestBody = requestBody;
    return this;
  }

  /**
   * Get requestBody
   * @return requestBody
   **/
  @JsonProperty("requestBody")
  @Schema(required = true, description = "")
  @NotNull
  @Valid
  public RequestBody getRequestBody() {
    return requestBody;
  }

  public void setRequest(RequestBody requestBody) {
    this.requestBody = requestBody;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestMessage restMessage = (RestMessage) o;
    return Objects.equals(this.requestHeader, restMessage.requestHeader) &&
        Objects.equals(this.requestBody, restMessage.requestBody);
  }

  @Override
  public int hashCode() {
    return Objects.hash(requestHeader, requestBody);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Dummy {\n");
    
    sb.append("    requestHeader: ").append(toIndentedString(requestHeader)).append("\n");
    sb.append("    requestBody: ").append(toIndentedString(requestBody)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
